import Head from 'next/head'
import { useState } from 'react';
import Navbar from '../components/Navbar'
import Summary from '../components/Summary';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark": "" }>
      <Head>
        <title>Mahmoud Makhlouf Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <Navbar setDarkMode={setDarkMode} darkMode={darkMode} />
          <Summary />
        </section>
        <Projects />
        <section>
          <Skills />
          <About />
        </section>
        <Contact />
      </main>
      
    </div>
  )
}
