import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mahmoud Makhlouf Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="min-h-screen">

        </section>
      </main>

      
    </div>
  )
}
